-- WTW Seed Current Site Data v2 JSONB format
-- Manual review only. Do not run automatically.
-- Source: events.html, all-events.html, event-detail.html, indulge.html, indulge-detail.html
-- Event date field: event_date
-- Duplicate protection: insert only when a matching row does not already exist.
-- Prepared counts: events=121, venues=41

WITH seed_events AS (
  SELECT *
  FROM jsonb_to_recordset(
    $wtw_seed$[
  {
    "title": "After-Dark Lounge",
    "venue_name": "After-Dark Lounge",
    "market": "NYC",
    "category": "latenight",
    "event_date": "2025-06-12",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "A lower downtown room with creative energy and a precise late-night door.",
    "music": "ART CROWD, AFTERHOURS",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "Downtown Supper Club",
    "venue_name": "Downtown Supper Club",
    "market": "NYC",
    "category": "premium",
    "event_date": "2025-06-12",
    "start_time": "20:00:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "description": "A polished social room for dinner, martinis, and discreet downtown access.",
    "music": "ITALIAN LUXURY, SOCIAL",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 55,
    "status": "available"
  },
  {
    "title": "Manhattan House Salon",
    "venue_name": "Manhattan House",
    "market": "NYC",
    "category": "premium",
    "event_date": "2025-06-14",
    "start_time": "20:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A polished Manhattan lounge night with fashion-table energy and quiet luxury pacing.",
    "music": "EDITORIAL, SALON",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 55,
    "status": "available"
  },
  {
    "title": "Williamsburg Glass Roof",
    "venue_name": "Glasshouse BK",
    "market": "NYC",
    "category": "rooftop",
    "event_date": "2025-06-14",
    "start_time": "19:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A Brooklyn rooftop with skyline views, creative regulars, and a clean guest-list lane.",
    "music": "BROOKLYN, ROOFTOP",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 38,
    "status": "guestlist"
  },
  {
    "title": "NoMad Listening Room",
    "venue_name": "NoMad Social",
    "market": "NYC",
    "category": "lounge",
    "event_date": "2025-06-15",
    "start_time": "20:00:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A low-volume cocktail room for vinyl selectors, martinis, and sharp conversation.",
    "music": "LISTENING ROOM, COCKTAILS",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 32,
    "status": "available"
  },
  {
    "title": "Queens Afrobeats Club",
    "venue_name": "Velvet Queens",
    "market": "NYC",
    "category": "latenight",
    "event_date": "2025-06-15",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "A stylish Queens room with Afrobeats, Amapiano, and late-night table momentum.",
    "music": "AFROBEATS, QUEENS",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 28,
    "status": "available"
  },
  {
    "title": "SoHo Members Dinner",
    "venue_name": "Crosby House",
    "market": "NYC",
    "category": "premium",
    "event_date": "2025-06-19",
    "start_time": "19:30:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "description": "A private-club inspired dinner-to-lounge room with downtown editorial polish.",
    "music": "MEMBERS ENERGY, SOHO",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 70,
    "status": null
  },
  {
    "title": "Lower East Side After Dark",
    "venue_name": "Orchard Room",
    "market": "NYC",
    "category": "latenight",
    "event_date": "2025-06-19",
    "start_time": "22:30:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A precise downtown late room with creative energy and a tighter door.",
    "music": "DOWNTOWN, AFTER DARK",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Hudson Terrace Tables",
    "venue_name": "Hudson Terrace",
    "market": "NYC",
    "category": "rooftop",
    "event_date": "2025-06-20",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1513326738677-b964603b136d?w=800&q=80&auto=format&fit=crop",
    "description": "A glossy west-side rooftop with skyline tables and elevated group energy.",
    "music": "HUDSON VIEWS, TABLES",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 48,
    "status": "available"
  },
  {
    "title": "Tribeca Champagne Room",
    "venue_name": "Atelier Tribeca",
    "market": "NYC",
    "category": "premium",
    "event_date": "2025-06-20",
    "start_time": "20:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80&auto=format&fit=crop",
    "description": "A refined champagne lounge with subtle luxury, polished service, and a selective crowd.",
    "music": "CHAMPAGNE, TRIBECA",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 60,
    "status": null
  },
  {
    "title": "Brooklyn Mirage Signal",
    "venue_name": "East River Hall",
    "market": "NYC",
    "category": "weekend",
    "event_date": "2025-06-21",
    "start_time": "22:00:00",
    "end_time": "04:00:00",
    "image_url": "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80&auto=format&fit=crop",
    "description": "A high-motion Brooklyn dance floor with production, DJs, and late-night demand.",
    "music": "DANCE FLOOR, BROOKLYN",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 42,
    "status": "available"
  },
  {
    "title": "Upper East Side Martini Hour",
    "venue_name": "Madison Lounge",
    "market": "NYC",
    "category": "lounge",
    "event_date": "2025-06-21",
    "start_time": "19:00:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80&auto=format&fit=crop",
    "description": "An uptown cocktail room with tailored styling, quieter pacing, and premium service.",
    "music": "MARTINI HOUR, UPTOWN",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 50,
    "status": "available"
  },
  {
    "title": "Joia Beach Sunset",
    "venue_name": "Joia Beach",
    "market": "Miami",
    "category": "rooftop",
    "event_date": "2025-06-12",
    "start_time": "18:00:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop",
    "description": "Barefoot-luxury beach club mood with skyline views and early-evening heat.",
    "music": "WATERFRONT, SUNSET",
    "dress_code": "Resort Chic",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Baoli Miami Nights",
    "venue_name": "Baoli Miami",
    "market": "Miami",
    "category": "premium",
    "event_date": "2025-06-12",
    "start_time": "21:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A dinner show that turns into a high-gloss South Beach room.",
    "music": "DINNER SHOW, SOUTH BEACH",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 50,
    "status": null
  },
  {
    "title": "Komodo After Dark",
    "venue_name": "Komodo",
    "market": "Miami",
    "category": "premium",
    "event_date": "2025-06-13",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80&auto=format&fit=crop",
    "description": "Brickell power dinner energy with a late-night lounge finish.",
    "music": "BRICKELL, DINNER CLUB",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "M2 Neon Fridays",
    "venue_name": "M2 Miami",
    "market": "Miami",
    "category": "latenight",
    "event_date": "2025-06-13",
    "start_time": "23:00:00",
    "end_time": "05:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A big-room South Beach dance night with neon production and late momentum.",
    "music": "NEON, DANCE FLOOR",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "guestlist"
  },
  {
    "title": "Sexy Fish Late Table",
    "venue_name": "Sexy Fish Miami",
    "market": "Miami",
    "category": "premium",
    "event_date": "2025-06-14",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "Maximalist dinner glamour with a late cocktail-room crowd.",
    "music": "BRICKELL GLAM, TABLES",
    "dress_code": "Statement",
    "age_requirement": "21+",
    "ticket_price": 65,
    "status": "available"
  },
  {
    "title": "Ocean Drive Neon Room",
    "venue_name": "Neon Palm",
    "market": "Miami",
    "category": "latenight",
    "event_date": "2025-06-14",
    "start_time": "23:00:00",
    "end_time": "05:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A neon South Beach room with Latin sets, bottle-service heat, and late momentum.",
    "music": "NEON, SOUTH BEACH",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 50,
    "status": "available"
  },
  {
    "title": "Brickell Yacht Social",
    "venue_name": "Marina Club",
    "market": "Miami",
    "category": "premium",
    "event_date": "2025-06-14",
    "start_time": "19:00:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop",
    "description": "Waterfront cocktails, yacht-weekend styling, and a polished Brickell crowd.",
    "music": "YACHT ENERGY, BRICKELL",
    "dress_code": "Resort Chic",
    "age_requirement": "21+",
    "ticket_price": 65,
    "status": "available"
  },
  {
    "title": "Little Havana Latin Luxe",
    "venue_name": "Calle Ocho Social",
    "market": "Miami",
    "category": "lounge",
    "event_date": "2025-06-15",
    "start_time": "20:30:00",
    "end_time": "01:30:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A warm Latin lounge night with cocktails, percussion, and refined local flavor.",
    "music": "LATIN LUXURY, LIVE RHYTHM",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "guestlist"
  },
  {
    "title": "Wynwood Art Club",
    "venue_name": "Canvas Room",
    "market": "Miami",
    "category": "weekend",
    "event_date": "2025-06-15",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "A style-forward Wynwood room with DJs, art crowd energy, and an easy late curve.",
    "music": "WYNWOOD, ART CROWD",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Faena Red Room",
    "venue_name": "Faena Social",
    "market": "Miami",
    "category": "premium",
    "event_date": "2025-06-19",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop",
    "description": "A cinematic hotel-lounge mood with velvet lighting and high-gloss Miami glamour.",
    "music": "HOTEL GLAM, RED ROOM",
    "dress_code": "Statement",
    "age_requirement": "21+",
    "ticket_price": 75,
    "status": null
  },
  {
    "title": "Bal Harbour Champagne",
    "venue_name": "Harbour Lounge",
    "market": "Miami",
    "category": "premium",
    "event_date": "2025-06-19",
    "start_time": "19:30:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80&auto=format&fit=crop",
    "description": "A quieter luxury lounge with champagne service, resort styling, and polished pacing.",
    "music": "CHAMPAGNE, BAL HARBOUR",
    "dress_code": "Resort Chic",
    "age_requirement": "21+",
    "ticket_price": 60,
    "status": "available"
  },
  {
    "title": "Downtown Celebrity Table",
    "venue_name": "Eleventh Floor",
    "market": "Miami",
    "category": "latenight",
    "event_date": "2025-06-20",
    "start_time": "00:00:00",
    "end_time": "05:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "A late downtown table room with celebrity-host energy and a high-demand door.",
    "music": "CELEBRITY TABLE, DOWNTOWN",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 70,
    "status": null
  },
  {
    "title": "Coconut Grove Sunset",
    "venue_name": "Grove Terrace",
    "market": "Miami",
    "category": "rooftop",
    "event_date": "2025-06-20",
    "start_time": "18:30:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A softer sunset lounge with terrace cocktails and relaxed premium energy.",
    "music": "SUNSET, GROVE",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 32,
    "status": "available"
  },
  {
    "title": "Design District Dinner Party",
    "venue_name": "Studio District",
    "market": "Miami",
    "category": "premium",
    "event_date": "2025-06-21",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "description": "A fashionable dinner-party room with polished service and camera-ready Miami styling.",
    "music": "DINNER PARTY, DESIGN DISTRICT",
    "dress_code": "Fashionable",
    "age_requirement": "21+",
    "ticket_price": 48,
    "status": "available"
  },
  {
    "title": "South Pointe After Dark",
    "venue_name": "Point Lounge",
    "market": "Miami",
    "category": "latenight",
    "event_date": "2025-06-21",
    "start_time": "22:30:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A South of Fifth late room with sleek cocktails, tables, and premium beach-side energy.",
    "music": "SOFI, LATE TABLE",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Doheny Room Late",
    "venue_name": "Doheny Room",
    "market": "LA",
    "category": "latenight",
    "event_date": "2025-06-12",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "An intimate late room with DJ sets and low-key celebrity traffic.",
    "music": "WEHO, LATE ROOM",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "guestlist"
  },
  {
    "title": "EP & LP Skyline",
    "venue_name": "EP & LP",
    "market": "LA",
    "category": "rooftop",
    "event_date": "2025-06-12",
    "start_time": "20:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=800&q=80&auto=format&fit=crop",
    "description": "A relaxed rooftop cocktail scene with clean views and an easy door.",
    "music": "SKYLINE, COCKTAILS",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Warwick Saturdays",
    "venue_name": "Warwick LA",
    "market": "LA",
    "category": "weekend",
    "event_date": "2025-06-13",
    "start_time": "22:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "A dressed-up Hollywood table room with high-production weekend energy.",
    "music": "HOLLYWOOD, TABLES",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": null
  },
  {
    "title": "Ysabel Garden Night",
    "venue_name": "Ysabel",
    "market": "LA",
    "category": "premium",
    "event_date": "2025-06-14",
    "start_time": "21:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A garden dinner room with soft lighting, industry tables, and WeHo ease.",
    "music": "GARDEN ROOM, DINNER",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": "available"
  },
  {
    "title": "Beverly Hills Velvet Hour",
    "venue_name": "Crescent Lounge",
    "market": "LA",
    "category": "premium",
    "event_date": "2025-06-14",
    "start_time": "20:00:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80&auto=format&fit=crop",
    "description": "A quiet-luxury lounge with martinis, tailored service, and a discreet celebrity-adjacent crowd.",
    "music": "BEVERLY HILLS, VELVET",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 65,
    "status": "available"
  },
  {
    "title": "Hollywood Hills Sunset",
    "venue_name": "Hillside Roof",
    "market": "LA",
    "category": "rooftop",
    "event_date": "2025-06-14",
    "start_time": "18:30:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=800&q=80&auto=format&fit=crop",
    "description": "A golden-hour rooftop with canyon light, clean cocktails, and a polished LA crowd.",
    "music": "SUNSET, HILLS",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "guestlist"
  },
  {
    "title": "Melrose Minimal Club",
    "venue_name": "Melrose Room",
    "market": "LA",
    "category": "latenight",
    "event_date": "2025-06-15",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A clean, low-lit club room with minimal production and industry regulars.",
    "music": "MINIMAL CLUB, MELROSE",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 38,
    "status": "available"
  },
  {
    "title": "Malibu Moon Dinner",
    "venue_name": "Coast House",
    "market": "LA",
    "category": "premium",
    "event_date": "2025-06-15",
    "start_time": "19:00:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop",
    "description": "A coastal dinner-to-lounge mood with ocean air, soft lighting, and luxury pacing.",
    "music": "MALIBU, COASTAL",
    "dress_code": "Resort Chic",
    "age_requirement": "21+",
    "ticket_price": 80,
    "status": null
  },
  {
    "title": "Arts District Warehouse",
    "venue_name": "District Hall",
    "market": "LA",
    "category": "lounge",
    "event_date": "2025-06-19",
    "start_time": "21:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "An industrial creative room with DJ sets, cocktails, and low-key style energy.",
    "music": "ARTS DISTRICT, WAREHOUSE",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 34,
    "status": "guestlist"
  },
  {
    "title": "Santa Monica Terrace",
    "venue_name": "Ocean Terrace",
    "market": "LA",
    "category": "rooftop",
    "event_date": "2025-06-19",
    "start_time": "19:30:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A clean terrace night with ocean-facing cocktails and relaxed Westside polish.",
    "music": "OCEAN VIEW, TERRACE",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": "available"
  },
  {
    "title": "West Hollywood Table Room",
    "venue_name": "Laurel Club",
    "market": "LA",
    "category": "premium",
    "event_date": "2025-06-20",
    "start_time": "22:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "A refined table-forward WeHo room with celebrity minimalism and a sharp late door.",
    "music": "WEHO, TABLES",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 55,
    "status": null
  },
  {
    "title": "Silver Lake Listening Bar",
    "venue_name": "Vinyl Room",
    "market": "LA",
    "category": "lounge",
    "event_date": "2025-06-20",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A refined listening bar with vinyl selectors, natural wine, and creative local energy.",
    "music": "VINYL, SILVER LAKE",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 28,
    "status": "available"
  },
  {
    "title": "Sunset Strip Afterparty",
    "venue_name": "Strip House",
    "market": "LA",
    "category": "latenight",
    "event_date": "2025-06-21",
    "start_time": "23:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80&auto=format&fit=crop",
    "description": "A high-demand Strip afterparty with music-industry energy and premium table flow.",
    "music": "AFTERPARTY, SUNSET STRIP",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 50,
    "status": "available"
  },
  {
    "title": "Downtown High Floor",
    "venue_name": "Aster Tower",
    "market": "LA",
    "category": "rooftop",
    "event_date": "2025-06-21",
    "start_time": "20:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1513326738677-b964603b136d?w=800&q=80&auto=format&fit=crop",
    "description": "A high-floor DTLA room with skyline views, lounge seating, and polished groups.",
    "music": "DTLA, HIGH FLOOR",
    "dress_code": "Fashionable",
    "age_requirement": "21+",
    "ticket_price": 42,
    "status": "available"
  },
  {
    "title": "Teak Rooftop Signal",
    "venue_name": "Teak",
    "market": "Hoboken",
    "category": "rooftop",
    "event_date": "2025-06-12",
    "start_time": "21:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A local rooftop night with DJ rotation and casual-premium access.",
    "music": "ROOFTOP, HOBOKEN",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 25,
    "status": "guestlist"
  },
  {
    "title": "Rooftop at Exchange",
    "venue_name": "Exchange Place Rooftop",
    "market": "Jersey City",
    "category": "rooftop",
    "event_date": "2025-06-12",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1513326738677-b964603b136d?w=800&q=80&auto=format&fit=crop",
    "description": "Skyline cocktail energy with a clean view across the river.",
    "music": "SKYLINE, COCKTAILS",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "Montclair Listening Room",
    "venue_name": "Faubourg",
    "market": "Montclair",
    "category": "lounge",
    "event_date": "2025-06-13",
    "start_time": "20:30:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80&auto=format&fit=crop",
    "description": "A refined North Jersey dinner-room night with a grown, stylish crowd.",
    "music": "SUBURBAN LUXURY, DINNER",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "Surf City After Dark",
    "venue_name": "Surf City",
    "market": "Jersey City",
    "category": "weekend",
    "event_date": "2025-06-13",
    "start_time": "21:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A waterfront room with summer energy and a late DJ curve.",
    "music": "WATERFRONT, DJ SET",
    "dress_code": "Casual Upscale",
    "age_requirement": "21+",
    "ticket_price": 25,
    "status": "available"
  },
  {
    "title": "NoHu Rooftop Table",
    "venue_name": "NoHu Rooftop",
    "market": "Weehawken",
    "category": "rooftop",
    "event_date": "2025-06-14",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1513326738677-b964603b136d?w=800&q=80&auto=format&fit=crop",
    "description": "A Hudson-facing rooftop with lounge seating and Manhattan lights.",
    "music": "HUDSON VIEWS, TABLES",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": null
  },
  {
    "title": "Hoboken Pier Lounge",
    "venue_name": "Pier House",
    "market": "Hoboken",
    "category": "lounge",
    "event_date": "2025-06-14",
    "start_time": "20:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1513326738677-b964603b136d?w=800&q=80&auto=format&fit=crop",
    "description": "A waterfront Hoboken lounge with polished local energy and Manhattan views.",
    "music": "HOBOKEN, WATERFRONT",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 32,
    "status": "available"
  },
  {
    "title": "Newark Culture Room",
    "venue_name": "Brick City Social",
    "market": "Newark",
    "category": "latenight",
    "event_date": "2025-06-14",
    "start_time": "21:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "A culture-forward Newark room with DJs, cocktails, and a stylish local crowd.",
    "music": "NEWARK, CULTURE ROOM",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 28,
    "status": "guestlist"
  },
  {
    "title": "JC Champagne Terrace",
    "venue_name": "Hudson Terrace JC",
    "market": "Jersey City",
    "category": "rooftop",
    "event_date": "2025-06-15",
    "start_time": "19:30:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A champagne-forward Jersey City terrace with skyline light and upscale groups.",
    "music": "CHAMPAGNE, JC SKYLINE",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 42,
    "status": "available"
  },
  {
    "title": "Montclair Supper Club",
    "venue_name": "Valley House",
    "market": "Montclair",
    "category": "premium",
    "event_date": "2025-06-15",
    "start_time": "19:00:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "description": "A refined suburban supper-club night with dinner, cocktails, and grown local luxury.",
    "music": "SUPPER CLUB, MONTCLAIR",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Edgewater Moon Lounge",
    "venue_name": "Moonline",
    "market": "Edgewater",
    "category": "lounge",
    "event_date": "2025-06-19",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A low-lit riverfront lounge with Manhattan views and premium local table demand.",
    "music": "EDGEWATER, RIVER VIEWS",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Newport Rooftop Signal",
    "venue_name": "Newport Roof",
    "market": "Jersey City",
    "category": "rooftop",
    "event_date": "2025-06-19",
    "start_time": "20:30:00",
    "end_time": "01:30:00",
    "image_url": "https://images.unsplash.com/photo-1513326738677-b964603b136d?w=800&q=80&auto=format&fit=crop",
    "description": "A Jersey City rooftop signal with DJs, skyline views, and clean guest-list access.",
    "music": "NEWPORT, ROOFTOP",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "guestlist"
  },
  {
    "title": "Asbury Late Room",
    "venue_name": "Boardwalk Room",
    "market": "Asbury Park",
    "category": "weekend",
    "event_date": "2025-06-20",
    "start_time": "21:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A shore-adjacent late room with DJs, cocktails, and premium weekend groups.",
    "music": "ASBURY, LATE ROOM",
    "dress_code": "Casual Upscale",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "Hoboken Dinner Party",
    "venue_name": "Washington Social",
    "market": "Hoboken",
    "category": "lounge",
    "event_date": "2025-06-20",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80&auto=format&fit=crop",
    "description": "A polished dinner-party room with local tables, cocktails, and strong Friday energy.",
    "music": "DINNER PARTY, HOBOKEN",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 36,
    "status": "available"
  },
  {
    "title": "JC Afrobeats Lounge",
    "venue_name": "Grove Room",
    "market": "Jersey City",
    "category": "latenight",
    "event_date": "2025-06-21",
    "start_time": "22:00:00",
    "end_time": "02:30:00",
    "image_url": "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80&auto=format&fit=crop",
    "description": "A stylish Jersey City Afrobeats lounge with late movement and local premium energy.",
    "music": "AFROBEATS, GROVE STREET",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 28,
    "status": "available"
  },
  {
    "title": "Alpine Private Lounge",
    "venue_name": "Alpine House",
    "market": "Alpine",
    "category": "premium",
    "event_date": "2025-06-21",
    "start_time": "20:00:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80&auto=format&fit=crop",
    "description": "A quiet North Jersey luxury lounge with private-room energy and polished service.",
    "music": "PRIVATE LOUNGE, NORTH JERSEY",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 55,
    "status": null
  },
  {
    "title": "Crescent Club Social",
    "venue_name": "Crescent Club",
    "market": "Dallas",
    "category": "premium",
    "event_date": "2025-06-12",
    "start_time": "19:00:00",
    "end_time": "23:30:00",
    "image_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80&auto=format&fit=crop",
    "description": "A quiet luxury room for power dinners, skyline cocktails, and old Dallas polish.",
    "music": "MEMBERS ENERGY, UPTOWN",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 65,
    "status": null
  },
  {
    "title": "Theory Nightclub",
    "venue_name": "Theory",
    "market": "Dallas",
    "category": "latenight",
    "event_date": "2025-06-12",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A late Uptown dance room with quick access and group-table demand.",
    "music": "UPTOWN, DJ SET",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "guestlist"
  },
  {
    "title": "Catbird High Floor",
    "venue_name": "Catbird",
    "market": "Dallas",
    "category": "rooftop",
    "event_date": "2025-06-13",
    "start_time": "20:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1545470348-9717d1e4ac85?w=800&q=80&auto=format&fit=crop",
    "description": "A design-forward cocktail room with downtown views and a style-aware crowd.",
    "music": "HIGH FLOOR, COCKTAILS",
    "dress_code": "Fashionable",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Citizen Dallas Tables",
    "venue_name": "Citizen Dallas",
    "market": "Dallas",
    "category": "weekend",
    "event_date": "2025-06-13",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "Bottle-service energy for Dallas groups that want a clean, high-trust room.",
    "music": "TABLES, UPTOWN",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": "available"
  },
  {
    "title": "HG Sply Rooftop",
    "venue_name": "HG Sply Co.",
    "market": "Dallas",
    "category": "rooftop",
    "event_date": "2025-06-14",
    "start_time": "19:30:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A relaxed rooftop for early groups, skyline light, and Dallas weekend starts.",
    "music": "LOWER GREENVILLE, ROOFTOP",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 25,
    "status": "available"
  },
  {
    "title": "Uptown Steakhouse After Dark",
    "venue_name": "Cedar Room",
    "market": "Dallas",
    "category": "premium",
    "event_date": "2025-06-14",
    "start_time": "21:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "description": "A steakhouse-to-lounge night with polished Dallas tables and late cocktails.",
    "music": "STEAKHOUSE, UPTOWN",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 50,
    "status": "available"
  },
  {
    "title": "Deep Ellum Bass Room",
    "venue_name": "Elm Hall",
    "market": "Dallas",
    "category": "latenight",
    "event_date": "2025-06-14",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A late Deep Ellum room with bass-heavy DJs, groups, and quick access.",
    "music": "DEEP ELLUM, BASS ROOM",
    "dress_code": "Casual Upscale",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "guestlist"
  },
  {
    "title": "Victory Park Sports Afterparty",
    "venue_name": "Victory Social",
    "market": "Dallas",
    "category": "weekend",
    "event_date": "2025-06-15",
    "start_time": "21:30:00",
    "end_time": "01:30:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "A post-game Dallas social room with elevated groups, DJs, and premium sports energy.",
    "music": "SPORTS AFTERPARTY, VICTORY PARK",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Knox District Lounge",
    "venue_name": "Knox House",
    "market": "Dallas",
    "category": "lounge",
    "event_date": "2025-06-15",
    "start_time": "20:00:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A refined Knox cocktail lounge with quiet luxury and a dressed-up local crowd.",
    "music": "KNOX, COCKTAILS",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": "available"
  },
  {
    "title": "Bishop Arts Listening Bar",
    "venue_name": "Bishop Vinyl",
    "market": "Dallas",
    "category": "lounge",
    "event_date": "2025-06-19",
    "start_time": "20:30:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A stylish listening bar with vinyl selectors, cocktails, and creative Dallas energy.",
    "music": "VINYL, BISHOP ARTS",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 25,
    "status": "available"
  },
  {
    "title": "Harwood Skyline Room",
    "venue_name": "Harwood Social",
    "market": "Dallas",
    "category": "rooftop",
    "event_date": "2025-06-19",
    "start_time": "19:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1545470348-9717d1e4ac85?w=800&q=80&auto=format&fit=crop",
    "description": "A skyline-facing Harwood room with polished cocktails and group tables.",
    "music": "SKYLINE, HARWOOD",
    "dress_code": "Fashionable",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Design District Champagne",
    "venue_name": "Design House",
    "market": "Dallas",
    "category": "premium",
    "event_date": "2025-06-20",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80&auto=format&fit=crop",
    "description": "A champagne-led lounge night with polished service and elevated design crowd energy.",
    "music": "CHAMPAGNE, DESIGN DISTRICT",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 55,
    "status": null
  },
  {
    "title": "Lower Greenville Rooftop",
    "venue_name": "Greenville Roof",
    "market": "Dallas",
    "category": "rooftop",
    "event_date": "2025-06-20",
    "start_time": "19:00:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A relaxed rooftop start with skyline light, groups, and accessible premium energy.",
    "music": "ROOFTOP, LOWER GREENVILLE",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 28,
    "status": "available"
  },
  {
    "title": "Highland Park Social",
    "venue_name": "Park Lane Club",
    "market": "Dallas",
    "category": "premium",
    "event_date": "2025-06-21",
    "start_time": "20:00:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80&auto=format&fit=crop",
    "description": "A quiet Dallas luxury room with private-club pacing and old-money polish.",
    "music": "HIGHLAND PARK, SOCIAL",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 65,
    "status": null
  },
  {
    "title": "Main Street Late Tables",
    "venue_name": "Main Room",
    "market": "Dallas",
    "category": "latenight",
    "event_date": "2025-06-21",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80&auto=format&fit=crop",
    "description": "A downtown late-table room with DJs, bottle service, and a clean premium door.",
    "music": "DOWNTOWN, LATE TABLES",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 38,
    "status": "available"
  },
  {
    "title": "Rock Steady Amapiano",
    "venue_name": "Rock Steady",
    "market": "Atlanta",
    "category": "lounge",
    "event_date": "2025-06-12",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "A culture-rich lounge night with Amapiano, Afrobeats, and a stylish crowd.",
    "music": "AMAPIANO, WEST MIDTOWN",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "Havana Club Sections",
    "venue_name": "Havana Club",
    "market": "Atlanta",
    "category": "premium",
    "event_date": "2025-06-12",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "A multi-room Buckhead club night with sections, DJs, and late table demand.",
    "music": "UPSCALE CLUB, BUCKHEAD",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "The James Room",
    "venue_name": "The James Room",
    "market": "Atlanta",
    "category": "lounge",
    "event_date": "2025-06-13",
    "start_time": "20:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A low-lit cocktail lounge with a refined local crowd and quiet Atlanta cool.",
    "music": "COCKTAIL LOUNGE, O4W",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 25,
    "status": "available"
  },
  {
    "title": "District Saturdays",
    "venue_name": "District Atlanta",
    "market": "Atlanta",
    "category": "weekend",
    "event_date": "2025-06-14",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80&auto=format&fit=crop",
    "description": "A polished late-night club room with production, bass, and premium tables.",
    "music": "DANCE FLOOR, WEST MIDTOWN",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": null
  },
  {
    "title": "Buckhead Velvet Table",
    "venue_name": "Velvet Buckhead",
    "market": "Atlanta",
    "category": "premium",
    "event_date": "2025-06-14",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "A velvet Buckhead table room with R&B, champagne, and polished Southern nightlife.",
    "music": "BUCKHEAD, VELVET TABLES",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Midtown R&B Social",
    "venue_name": "Peachtree Social",
    "market": "Atlanta",
    "category": "lounge",
    "event_date": "2025-06-14",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A grown Midtown R&B night with cocktails, dressed-up groups, and a calm premium door.",
    "music": "R&B, MIDTOWN",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "guestlist"
  },
  {
    "title": "West Midtown Afrobeats",
    "venue_name": "Westside Room",
    "market": "Atlanta",
    "category": "latenight",
    "event_date": "2025-06-15",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "Afrobeats and Amapiano in a stylish West Midtown room with late-night movement.",
    "music": "AFROBEATS, WEST MIDTOWN",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 32,
    "status": "available"
  },
  {
    "title": "Ponce Rooftop Lounge",
    "venue_name": "Ponce Roof",
    "market": "Atlanta",
    "category": "rooftop",
    "event_date": "2025-06-15",
    "start_time": "19:00:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A relaxed rooftop lounge with city views, cocktails, and premium local pacing.",
    "music": "PONCE, ROOFTOP",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "Celebrity Room ATL",
    "venue_name": "Peachtree Club",
    "market": "Atlanta",
    "category": "premium",
    "event_date": "2025-06-19",
    "start_time": "22:30:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop",
    "description": "A celebrity-style Buckhead room with section demand and polished host energy.",
    "music": "CELEBRITY ROOM, BUCKHEAD",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 55,
    "status": null
  },
  {
    "title": "Inman Park Cocktail House",
    "venue_name": "Inman House",
    "market": "Atlanta",
    "category": "lounge",
    "event_date": "2025-06-19",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A neighborhood cocktail room with tasteful music, stylish locals, and warm Southern service.",
    "music": "COCKTAIL HOUSE, INMAN PARK",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 28,
    "status": "available"
  },
  {
    "title": "Downtown Late Suite",
    "venue_name": "Suite District",
    "market": "Atlanta",
    "category": "latenight",
    "event_date": "2025-06-20",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "A downtown late suite with DJs, sections, and Southern premium nightlife energy.",
    "music": "DOWNTOWN, LATE SUITE",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 38,
    "status": "available"
  },
  {
    "title": "BeltLine Dinner Party",
    "venue_name": "BeltLine Social",
    "market": "Atlanta",
    "category": "lounge",
    "event_date": "2025-06-20",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "description": "A dinner-party rhythm near the BeltLine with cocktails, DJs, and easy premium energy.",
    "music": "DINNER PARTY, BELTLINE",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 34,
    "status": "available"
  },
  {
    "title": "Amapiano Garden Room",
    "venue_name": "Garden Room ATL",
    "market": "Atlanta",
    "category": "lounge",
    "event_date": "2025-06-21",
    "start_time": "21:30:00",
    "end_time": "02:30:00",
    "image_url": "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80&auto=format&fit=crop",
    "description": "A lush Midtown garden-room mood with Amapiano, Afrobeats, and a polished crowd.",
    "music": "AMAPIANO, GARDEN ROOM",
    "dress_code": "Fashionable",
    "age_requirement": "21+",
    "ticket_price": 36,
    "status": "available"
  },
  {
    "title": "Southern Luxury Social",
    "venue_name": "Magnolia Club",
    "market": "Atlanta",
    "category": "premium",
    "event_date": "2025-06-21",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1528605248644-14dd04022da1?w=800&q=80&auto=format&fit=crop",
    "description": "A polished Southern luxury lounge with champagne, R&B, and high-trust table access.",
    "music": "SOUTHERN LUXURY, BUCKHEAD",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 50,
    "status": null
  },
  {
    "title": "Downtown Night Room",
    "venue_name": "Downtown Night Room",
    "market": "NYC",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "23:00:00",
    "end_time": "04:00:00",
    "image_url": "assets/img/venue-marquee.jpg",
    "description": "World-class DJs, immersive production, and the city's most watched room.",
    "music": "HIGH ENERGY, PREMIUM TABLES",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 65,
    "status": "available"
  },
  {
    "title": "SoHo Members Lounge",
    "venue_name": "SoHo Members Lounge",
    "market": "NYC",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "assets/img/venue-nines.jpg",
    "description": "A velvet downtown room for sharp cocktails, music heads, and late conversation.",
    "music": "PIANO LOUNGE, UPSCALE",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "high-interest"
  },
  {
    "title": "NoHo Selects",
    "venue_name": "NoHo Selects Lounge",
    "market": "NYC",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "22:30:00",
    "end_time": "02:30:00",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop",
    "description": "A private-club style night with fashion week energy and a selective door.",
    "music": "MEMBERS ENERGY, EDITORIAL",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 75,
    "status": "high-interest"
  },
  {
    "title": "Rooftop Social Club",
    "venue_name": "Rooftop Social Club",
    "market": "NYC",
    "category": "rooftop",
    "event_date": "2025-06-07",
    "start_time": "20:00:00",
    "end_time": "02:00:00",
    "image_url": "assets/img/venue-phd.jpg",
    "description": "Manhattan skyline, polished cocktails, and a curated rooftop crowd.",
    "music": "ROOFTOP, SKYLINE VIEWS",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": "available"
  },
  {
    "title": "Afrowave Saturdays",
    "venue_name": "Midtown Sky Lounge",
    "market": "NYC",
    "category": "rooftop",
    "event_date": "2025-06-07",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "assets/img/venue-phd.jpg",
    "description": "Afrobeats, Amapiano, and dancehall above the city with open-air energy.",
    "music": "AFROBEATS, ROOFTOP",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "Midtown Dinner Club",
    "venue_name": "Midtown Dinner Club",
    "market": "NYC",
    "category": "weekend",
    "event_date": "2025-06-07",
    "start_time": "23:00:00",
    "end_time": "04:00:00",
    "image_url": "assets/img/venue-marquee.jpg",
    "description": "A dinner-to-dance room where celebrity culture meets Midtown polish.",
    "music": "DINNER CLUB, LATE NIGHT",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Waterfront Dinner House",
    "venue_name": "Waterfront Dinner House",
    "market": "NYC",
    "category": "rooftop",
    "event_date": "2025-06-08",
    "start_time": "19:00:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "East River views, fashion crowd, and a slower Sunday room.",
    "music": "MEMBERS ROOFTOP, SUNSET",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 50,
    "status": "available"
  },
  {
    "title": "Downtown Social Room",
    "venue_name": "Downtown Social Room",
    "market": "NYC",
    "category": "weekend",
    "event_date": "2025-06-08",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "assets/img/venue-nines.jpg",
    "description": "A downtown dinner club rhythm with Latin, reggaeton, and champagne-table energy.",
    "music": "DINNER CLUB, GUEST LIST",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 25,
    "status": "guestlist"
  },
  {
    "title": "LIV Saturday",
    "venue_name": "LIV Miami",
    "market": "Miami",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "23:59:00",
    "end_time": "05:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "The world-famous room for A-list DJs, camera flashes, and peak Miami energy.",
    "music": "CELEBRITY, SOUTH BEACH",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 80,
    "status": "high-interest"
  },
  {
    "title": "E11EVEN All Night",
    "venue_name": "E11EVEN Miami",
    "market": "Miami",
    "category": "tonight",
    "event_date": "2025-06-07",
    "start_time": "00:30:00",
    "end_time": null,
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop",
    "description": "A neon, no-sleep room with performers, bottle service, and downtown heat.",
    "music": "24 HOURS, ULTRA PREMIUM",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 60,
    "status": "available"
  },
  {
    "title": "Kiki on the River",
    "venue_name": "Kiki on the River",
    "market": "Miami",
    "category": "weekend",
    "event_date": "2025-06-07",
    "start_time": "20:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop",
    "description": "Dinner party glamour on the river with champagne, boats, and Miami social energy.",
    "music": "DINNER PARTY, RIVER",
    "dress_code": "Chic",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Story Sunday",
    "venue_name": "Story Miami",
    "market": "Miami",
    "category": "weekend",
    "event_date": "2025-06-08",
    "start_time": "23:00:00",
    "end_time": "04:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "International headliners and full-production dance floor energy every weekend.",
    "music": "EDM, DANCE FLOOR",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 55,
    "status": "available"
  },
  {
    "title": "Swan Room Social",
    "venue_name": "Swan",
    "market": "Miami",
    "category": "lounge",
    "event_date": "2025-06-08",
    "start_time": "20:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "Fashionable dinner-room energy with polished cocktails and a dressed-up crowd.",
    "music": "DESIGN DISTRICT, DINNER CLUB",
    "dress_code": "Fashionable",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": "available"
  },
  {
    "title": "Poppy Fridays",
    "venue_name": "Poppy",
    "market": "LA",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "22:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "A cinematic WeHo room where the entertainment crowd comes to be seen.",
    "music": "CELEBRITY CROWD, LATE NIGHT",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 50,
    "status": "available"
  },
  {
    "title": "Delilah Dinner Club",
    "venue_name": "Delilah WeHo",
    "market": "LA",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80&auto=format&fit=crop",
    "description": "Art deco supper-club polish with live music and discreet celebrity energy.",
    "music": "DINNER CLUB, ART DECO",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Sunset Tower Salon",
    "venue_name": "Sunset Tower",
    "market": "LA",
    "category": "weekend",
    "event_date": "2025-06-07",
    "start_time": "19:30:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&q=80&auto=format&fit=crop",
    "description": "A quiet Hollywood salon mood for martinis, views, and old-guard glamour.",
    "music": "OLD HOLLYWOOD, SALON",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 60,
    "status": "high-interest"
  },
  {
    "title": "Highlight Room Sunsets",
    "venue_name": "Highlight Room",
    "market": "LA",
    "category": "rooftop",
    "event_date": "2025-06-07",
    "start_time": "18:00:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop",
    "description": "Hollywood hills, sunset light, and a polished rooftop crowd.",
    "music": "ROOFTOP, GOLDEN HOUR",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": "guestlist"
  },
  {
    "title": "Nobu Malibu Afterdark",
    "venue_name": "Nobu Malibu",
    "market": "LA",
    "category": "premium",
    "event_date": "2025-06-08",
    "start_time": "19:00:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80&auto=format&fit=crop",
    "description": "Coastal dinner energy that moves from ocean light into a late table scene.",
    "music": "COASTAL LUXURY, DINNER",
    "dress_code": "Resort Chic",
    "age_requirement": "21+",
    "ticket_price": 75,
    "status": "available"
  },
  {
    "title": "Soho Warehouse Roof",
    "venue_name": "Soho Warehouse",
    "market": "LA",
    "category": "rooftop",
    "event_date": "2025-06-08",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A calm creative rooftop with downtown views and industry regulars.",
    "music": "ARTS DISTRICT, MEMBERS ENERGY",
    "dress_code": "Creative Upscale",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Porta Rooftop Weekend",
    "venue_name": "Porta",
    "market": "Jersey City",
    "category": "rooftop",
    "event_date": "2025-06-06",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "assets/img/venue-phd.jpg",
    "description": "Jersey City rooftop energy with Manhattan views and a polished local crowd.",
    "music": "ROOFTOP, SKYLINE",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "The Ashford Late",
    "venue_name": "The Ashford",
    "market": "Jersey City",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "22:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop",
    "description": "A reliable downtown room with bar energy, DJs, and an easy guest-list window.",
    "music": "DOWNTOWN JC, LATE ROOM",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 25,
    "status": "guestlist"
  },
  {
    "title": "Hoboken Social House",
    "venue_name": "Antique Bar & Bakery",
    "market": "Hoboken",
    "category": "weekend",
    "event_date": "2025-06-07",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A refined Hoboken dinner-to-drinks night with local premium energy.",
    "music": "HOBOKEN, SOCIAL",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Battello Skyline Dinner",
    "venue_name": "Battello",
    "market": "Jersey City",
    "category": "premium",
    "event_date": "2025-06-07",
    "start_time": "19:30:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "description": "Waterfront dinner, skyline views, and a dressed-up Jersey City room.",
    "music": "WATERFRONT, DINNER",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Dullboy Cocktail Night",
    "venue_name": "Dullboy",
    "market": "Jersey City",
    "category": "lounge",
    "event_date": "2025-06-08",
    "start_time": "20:30:00",
    "end_time": "00:30:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A low-lit cocktail room for a sharper Sunday crowd.",
    "music": "COCKTAILS, LOW LIT",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 20,
    "status": "available"
  },
  {
    "title": "Komodo Dallas Friday",
    "venue_name": "Komodo Dallas",
    "market": "Dallas",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "21:00:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "A high-gloss dinner club with Dallas table culture and a late room finish.",
    "music": "UPSCALE, TABLES",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 55,
    "status": "available"
  },
  {
    "title": "Monarch Skyline Dinner",
    "venue_name": "Monarch",
    "market": "Dallas",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "19:30:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop",
    "description": "Downtown skyline luxury with Italian dining and a sharp social room.",
    "music": "SKYLINE, DINNER",
    "dress_code": "Cocktail",
    "age_requirement": "21+",
    "ticket_price": 60,
    "status": "available"
  },
  {
    "title": "Happiest Hour Rooftop",
    "venue_name": "Happiest Hour",
    "market": "Dallas",
    "category": "rooftop",
    "event_date": "2025-06-07",
    "start_time": "20:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "A big Dallas rooftop for game-weekend energy and easy group access.",
    "music": "ROOFTOP, SPORTS WEEKEND",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "guestlist"
  },
  {
    "title": "XOXO Dining Room",
    "venue_name": "XOXO Dining Room",
    "market": "Dallas",
    "category": "weekend",
    "event_date": "2025-06-07",
    "start_time": "21:00:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop",
    "description": "A playful dinner-room scene with dressed-up groups and strong photo energy.",
    "music": "DINNER PARTY, SOCIAL",
    "dress_code": "Fashionable",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Midnight Rambler",
    "venue_name": "Midnight Rambler",
    "market": "Dallas",
    "category": "lounge",
    "event_date": "2025-06-08",
    "start_time": "21:30:00",
    "end_time": "01:30:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A subterranean cocktail room for late drinks and polished downtown energy.",
    "music": "COCKTAIL DEN, LOW LIT",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 25,
    "status": "available"
  },
  {
    "title": "Gold Room Fridays",
    "venue_name": "Gold Room",
    "market": "Atlanta",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "22:30:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80&auto=format&fit=crop",
    "description": "Buckhead section culture with celebrity-host energy and a polished late room.",
    "music": "BUCKHEAD, PREMIUM SECTIONS",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 45,
    "status": "available"
  },
  {
    "title": "Rose Bar R&B",
    "venue_name": "Rose Bar",
    "market": "Atlanta",
    "category": "tonight",
    "event_date": "2025-06-06",
    "start_time": "21:30:00",
    "end_time": "02:00:00",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80&auto=format&fit=crop",
    "description": "A grown Buckhead lounge with R&B, cocktails, and polished table energy.",
    "music": "R&B, BUCKHEAD",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Virtue Rooftop Sessions",
    "venue_name": "Virtue Rooftop",
    "market": "Atlanta",
    "category": "rooftop",
    "event_date": "2025-06-07",
    "start_time": "19:30:00",
    "end_time": "01:00:00",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80&auto=format&fit=crop",
    "description": "Midtown skyline cocktails with an easy premium rooftop rhythm.",
    "music": "MIDTOWN, ROOFTOP",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "guestlist"
  },
  {
    "title": "Suite Lounge Afrobeats",
    "venue_name": "Suite Food Lounge",
    "market": "Atlanta",
    "category": "weekend",
    "event_date": "2025-06-07",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80&auto=format&fit=crop",
    "description": "Afrobeats, Amapiano, and Atlanta late-night crowd movement downtown.",
    "music": "AFROBEATS, LATE ROOM",
    "dress_code": "Casual Upscale",
    "age_requirement": "21+",
    "ticket_price": 35,
    "status": "available"
  },
  {
    "title": "Opium Celebrity Lounge",
    "venue_name": "Opium Atlanta",
    "market": "Atlanta",
    "category": "premium",
    "event_date": "2025-06-08",
    "start_time": "22:30:00",
    "end_time": "03:00:00",
    "image_url": "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80&auto=format&fit=crop",
    "description": "A high-demand celebrity lounge with table-forward Southern nightlife energy.",
    "music": "CELEBRITY LOUNGE, TABLES",
    "dress_code": "Upscale",
    "age_requirement": "21+",
    "ticket_price": 40,
    "status": "high-interest"
  },
  {
    "title": "SkyLounge Sunset",
    "venue_name": "SkyLounge",
    "market": "Atlanta",
    "category": "rooftop",
    "event_date": "2025-06-08",
    "start_time": "18:30:00",
    "end_time": "00:00:00",
    "image_url": "https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800&q=80&auto=format&fit=crop",
    "description": "Downtown skyline, Southern hospitality, and a clean sunset-to-late transition.",
    "music": "SKYLINE, SUNSET",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  },
  {
    "title": "Midtown Sky Lounge",
    "venue_name": "Midtown Sky Lounge",
    "market": "NYC",
    "category": "rooftop",
    "event_date": "2025-06-07",
    "start_time": "22:00:00",
    "end_time": "03:00:00",
    "image_url": "assets/img/venue-phd.jpg",
    "description": "Afrobeats, Amapiano, and dancehall above the city with open-air energy.",
    "music": "AFROBEATS, ROOFTOP",
    "dress_code": "Smart Casual",
    "age_requirement": "21+",
    "ticket_price": 30,
    "status": "available"
  }
]$wtw_seed$::jsonb
  ) AS v (
    title text,
    venue_name text,
    market text,
    category text,
    event_date date,
    start_time time,
    end_time time,
    image_url text,
    description text,
    music text,
    dress_code text,
    age_requirement text,
    ticket_price numeric,
    status text
  )
)
INSERT INTO public.events (
  title,
  venue_name,
  market,
  category,
  event_date,
  start_time,
  end_time,
  image_url,
  description,
  music,
  dress_code,
  age_requirement,
  ticket_price,
  status
)
SELECT
  v.title,
  v.venue_name,
  v.market,
  v.category,
  v.event_date,
  v.start_time,
  v.end_time,
  v.image_url,
  v.description,
  v.music,
  v.dress_code,
  v.age_requirement,
  v.ticket_price,
  v.status
FROM seed_events v
WHERE NOT EXISTS (
  SELECT 1
  FROM public.events e
  WHERE lower(coalesce(e.title, '')) = lower(coalesce(v.title, ''))
    AND e.market = v.market
    AND e.event_date = v.event_date
    AND lower(coalesce(e.venue_name, '')) = lower(coalesce(v.venue_name, ''))
);

WITH seed_venues AS (
  SELECT *
  FROM jsonb_to_recordset(
    $wtw_seed$[
  {
    "name": "Frevo",
    "market": "NYC",
    "type": "Dinner",
    "neighborhood": "Greenwich Village",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Michelin-starred tasting room",
    "best_for": "Date Night",
    "dress_code": "Smart Casual",
    "description": "One of NYC's most talked-about 2026 openings. Already Michelin-starred, Frevo is a Greenwich Village tasting room built for guests who treat dinner as the main event."
  },
  {
    "name": "The Eighty Six",
    "market": "NYC",
    "type": "Dinner",
    "neighborhood": "West Village",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Hot new West Village dinner room",
    "best_for": "Date Night",
    "dress_code": "Cocktail",
    "description": "86 Bedford St — one of the most talked-about West Village openings of 2026. A composed dinner room with a late lounge pulse that keeps the right crowd through the evening."
  },
  {
    "name": "10Cubed",
    "market": "NYC",
    "type": "Dinner",
    "neighborhood": "Midtown",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "100th floor skyline dining",
    "best_for": "Birthday",
    "dress_code": "Cocktail",
    "description": "217 West 57th St, 100 floors above Manhattan. Panoramic Central Park views, private dining rooms, a cigar lounge, and an intimate nightclub — built for nights that need to be remembered."
  },
  {
    "name": "Rooftop Social Club",
    "market": "NYC",
    "type": "Rooftop",
    "neighborhood": "Chelsea",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Sunset rooftop to late-night club",
    "best_for": "Birthday",
    "dress_code": "Smart Casual",
    "description": "Chelsea's rooftop that transitions from golden-hour cocktails to a high-energy dance floor. Skyline views, premium pricing, and a crowd that arrives for sunset and stays for the night."
  },
  {
    "name": "The DL",
    "market": "NYC",
    "type": "Rooftop",
    "neighborhood": "Lower East Side",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Three-level rooftop club and bistro",
    "best_for": "Turns Into Nightlife",
    "dress_code": "Smart Casual",
    "description": "An iconic LES three-level venue with NYC's best retractable rooftop, a private DJ lounge on the second floor, and Le Jardin Bistro for French-inspired dinner on the first. One venue, full night."
  },
  {
    "name": "Little Sister Lounge",
    "market": "NYC",
    "type": "After Work",
    "neighborhood": "East Village",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$",
    "atmosphere": "Intimate after-midnight lounge",
    "best_for": "Turns Into Nightlife",
    "dress_code": "Cocktail",
    "description": "Tucked beneath the Moxy East Village — jewel-toned interiors, low ceilings, intimate corners, and a crowd that dresses like the night matters. The right room after dinner anywhere downtown."
  },
  {
    "name": "Hudson House Rooftop",
    "market": "NJ",
    "type": "Rooftop",
    "neighborhood": "Jersey City",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Skyline rooftop",
    "best_for": "Birthday",
    "dress_code": "Smart Casual",
    "description": "Manhattan views without the Manhattan friction, built for groups and polished dinners."
  },
  {
    "name": "Hoboken Supper Lounge",
    "market": "NJ",
    "type": "Dinner",
    "neighborhood": "Hoboken",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Local upscale lounge",
    "best_for": "Date Night",
    "dress_code": "Cocktail",
    "description": "A warm dinner lounge that moves into cocktails and music after the first seating."
  },
  {
    "name": "Newark Velvet Room",
    "market": "NJ",
    "type": "Dinner",
    "neighborhood": "Newark",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "R&B dinner room",
    "best_for": "Birthday",
    "dress_code": "Cocktail",
    "description": "Upscale local energy with R&B, bottle moments, and birthday-ready tables."
  },
  {
    "name": "Newport Terrace",
    "market": "NJ",
    "type": "After Work",
    "neighborhood": "Newport",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Waterfront cocktails",
    "best_for": "After Work",
    "dress_code": "Smart Casual",
    "description": "Clean skyline cocktails for work groups, dates, and calm pre-nightlife starts."
  },
  {
    "name": "Montclair Social",
    "market": "NJ",
    "type": "Dinner",
    "neighborhood": "Montclair",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Neighborhood prestige",
    "best_for": "Date Night",
    "dress_code": "Smart Casual",
    "description": "A refined local room for couples and small groups that want quality over noise."
  },
  {
    "name": "Edgewater Night Table",
    "market": "NJ",
    "type": "Dinner",
    "neighborhood": "Edgewater",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Riverfront dinner lounge",
    "best_for": "Turns Into Nightlife",
    "dress_code": "Cocktail",
    "description": "Riverfront dinner, late cocktails, and a room that keeps its energy after 10."
  },
  {
    "name": "South Beach Pearl",
    "market": "Miami",
    "type": "Dinner",
    "neighborhood": "South Beach",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Celebrity dinner lounge",
    "best_for": "Birthday",
    "dress_code": "Cocktail",
    "description": "Glossy Miami dinner energy with champagne, cameras, and a late-room finish."
  },
  {
    "name": "Brickell Terrace",
    "market": "Miami",
    "type": "Rooftop",
    "neighborhood": "Brickell",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Rooftop power dinner",
    "best_for": "After Work",
    "dress_code": "Smart Casual",
    "description": "Skyline cocktails, polished tables, and a smooth bridge from dinner into nightlife."
  },
  {
    "name": "Little Havana Gold",
    "market": "Miami",
    "type": "Dinner",
    "neighborhood": "Little Havana",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Latin luxury",
    "best_for": "Date Night",
    "dress_code": "Cocktail",
    "description": "Warm Latin dining, live rhythm, and a seductive room built for dates and groups."
  },
  {
    "name": "Ocean Drive Brunch Club",
    "market": "Miami",
    "type": "Brunch",
    "neighborhood": "Miami Beach",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Brunch-to-day-party",
    "best_for": "Brunch",
    "dress_code": "Smart Casual",
    "description": "A resort-chic brunch table that rolls into day-party energy by the water."
  },
  {
    "name": "Design District Salon",
    "market": "Miami",
    "type": "Dinner",
    "neighborhood": "Design District",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Fashion dinner room",
    "best_for": "Date Night",
    "dress_code": "Smart Casual",
    "description": "Art, fashion, and a quieter luxury dinner room for people who arrive dressed."
  },
  {
    "name": "River Yacht Table",
    "market": "Miami",
    "type": "Dinner",
    "neighborhood": "Miami River",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Waterfront dinner party",
    "best_for": "Turns Into Nightlife",
    "dress_code": "Cocktail",
    "description": "Boats, bottles, dinner, and a Miami room that keeps moving deep into the night."
  },
  {
    "name": "Buckhead Rose Room",
    "market": "Atlanta",
    "type": "Dinner",
    "neighborhood": "Buckhead",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "R&B dinner lounge",
    "best_for": "Birthday",
    "dress_code": "Cocktail",
    "description": "Southern luxury with R&B pacing, sections, and a room that comes alive late."
  },
  {
    "name": "Midtown Afrobeats Table",
    "market": "Atlanta",
    "type": "Dinner",
    "neighborhood": "Midtown",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Afrobeats dinner lounge",
    "best_for": "Turns Into Nightlife",
    "dress_code": "Cocktail",
    "description": "Dinner, cocktails, and Afrobeats momentum for groups that want movement after 10."
  },
  {
    "name": "Westside Supper Yard",
    "market": "Atlanta",
    "type": "Dinner",
    "neighborhood": "Westside",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Open-air dinner",
    "best_for": "After Work",
    "dress_code": "Cocktail",
    "description": "A polished outdoor room for after-work drinks that can turn into a full night."
  },
  {
    "name": "Peachtree Terrace",
    "market": "Atlanta",
    "type": "Rooftop",
    "neighborhood": "Downtown",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Skyline rooftop",
    "best_for": "Date Night",
    "dress_code": "Smart Casual",
    "description": "Clean skyline views and date-night energy with enough polish for a special ask."
  },
  {
    "name": "Velvet Southern Table",
    "market": "Atlanta",
    "type": "Dinner",
    "neighborhood": "Old Fourth Ward",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Southern luxury dining",
    "best_for": "Date Night",
    "dress_code": "Smart Casual",
    "description": "A composed Southern dinner room with low lighting, strong cocktails, and privacy."
  },
  {
    "name": "Cascade Brunch House",
    "market": "Atlanta",
    "type": "Brunch",
    "neighborhood": "Cascade",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Brunch-to-day-party",
    "best_for": "Brunch",
    "dress_code": "Smart Casual",
    "description": "A stylish brunch room with music, groups, and celebratory daytime energy."
  },
  {
    "name": "WeHo Velvet Supper",
    "market": "LA",
    "type": "Dinner",
    "neighborhood": "West Hollywood",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Celebrity minimalist",
    "best_for": "Date Night",
    "dress_code": "Cocktail",
    "description": "A quiet-luxury supper room with industry energy and a seamless late lounge."
  },
  {
    "name": "Hollywood Roofline",
    "market": "LA",
    "type": "Rooftop",
    "neighborhood": "Hollywood",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Rooftop city lights",
    "best_for": "Birthday",
    "dress_code": "Smart Casual",
    "description": "Sunset tables, city lights, and a social crowd that keeps the night elevated."
  },
  {
    "name": "Malibu Coast Table",
    "market": "LA",
    "type": "Dinner",
    "neighborhood": "Malibu",
    "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Coastal dinner",
    "best_for": "Date Night",
    "dress_code": "Smart Casual",
    "description": "A slower coastal dinner for dates, anniversaries, and premium daylight plans."
  },
  {
    "name": "Melrose Listening Lounge",
    "market": "LA",
    "type": "After Work",
    "neighborhood": "Melrose",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Cocktail lounge",
    "best_for": "After Work",
    "dress_code": "Smart Casual",
    "description": "Industry cocktails, minimal design, and a room built for conversation before night moves."
  },
  {
    "name": "Arts District Fire Table",
    "market": "LA",
    "type": "Dinner",
    "neighborhood": "Arts District",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Creative dinner party",
    "best_for": "Turns Into Nightlife",
    "dress_code": "Cocktail",
    "description": "A creative dinner room with DJs, mezcal, and a crowd that gets sharper late."
  },
  {
    "name": "Beverly Garden Brunch",
    "market": "LA",
    "type": "Brunch",
    "neighborhood": "Beverly Hills",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Luxury brunch",
    "best_for": "Brunch",
    "dress_code": "Smart Casual",
    "description": "A polished brunch setting for birthdays, soft launches, and daytime celebration."
  },
  {
    "name": "Uptown Monarch",
    "market": "Dallas",
    "type": "Dinner",
    "neighborhood": "Uptown Dallas",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Steakhouse lounge",
    "best_for": "Birthday",
    "dress_code": "Cocktail",
    "description": "Prime dinner energy with a lounge finish, built for celebrations and big tables."
  },
  {
    "name": "Deep Ellum Velvet",
    "market": "Dallas",
    "type": "Dinner",
    "neighborhood": "Deep Ellum",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Music dinner lounge",
    "best_for": "Turns Into Nightlife",
    "dress_code": "Cocktail",
    "description": "Live sound, polished cocktails, and enough edge to carry the night forward."
  },
  {
    "name": "Victory Park Terrace",
    "market": "Dallas",
    "type": "Rooftop",
    "neighborhood": "Victory Park",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Sports luxury rooftop",
    "best_for": "After Work",
    "dress_code": "Smart Casual",
    "description": "Game-night energy, skyline cocktails, and a premium pre/post-event crowd."
  },
  {
    "name": "Highland Park Table",
    "market": "Dallas",
    "type": "Dinner",
    "neighborhood": "Highland Park",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Quiet luxury dinner",
    "best_for": "Date Night",
    "dress_code": "Smart Casual",
    "description": "A composed dinner room for dates, clients, and elevated low-volume nights."
  },
  {
    "name": "Bishop Arts Brunch",
    "market": "Dallas",
    "type": "Brunch",
    "neighborhood": "Bishop Arts",
    "image_url": "https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$",
    "atmosphere": "Brunch social",
    "best_for": "Brunch",
    "dress_code": "Smart Casual",
    "description": "Stylish daytime energy for birthdays, groups, and brunch that feels intentional."
  },
  {
    "name": "Design District Gold Room",
    "market": "Dallas",
    "type": "After Work",
    "neighborhood": "Design District",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Upscale cocktail lounge",
    "best_for": "After Work",
    "dress_code": "Smart Casual",
    "description": "A polished drinks-first room for after-work, small groups, and late dinner decisions."
  },
  {
    "name": "Downtown Supper Club",
    "market": "NYC",
    "type": "Dinner",
    "neighborhood": "SoHo",
    "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Editorial dining lounge",
    "best_for": "Date Night",
    "dress_code": "Cocktail",
    "description": "A downtown dinner room with fashion-table energy, martinis, and a late lounge pulse."
  },
  {
    "name": "NoHo Listening Room",
    "market": "NYC",
    "type": "After Work",
    "neighborhood": "NoHo",
    "image_url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Members-club cocktails",
    "best_for": "After Work",
    "dress_code": "Smart Casual",
    "description": "Low-volume cocktails, vinyl selectors, and a polished room for quieter power dinners."
  },
  {
    "name": "Private Salon Lounge",
    "market": "NYC",
    "type": "Dinner",
    "neighborhood": "Tribeca",
    "image_url": "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$$",
    "atmosphere": "Private dining salon",
    "best_for": "Birthday",
    "dress_code": "Cocktail",
    "description": "A refined dinner-to-lounge setting for birthdays, client dinners, and late champagne."
  },
  {
    "name": "Dumbo Sunset Table",
    "market": "NYC",
    "type": "Rooftop",
    "neighborhood": "Brooklyn",
    "image_url": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Waterfront rooftop",
    "best_for": "Date Night",
    "dress_code": "Smart Casual",
    "description": "East River views and slower luxury for dates, golden hour, and small groups."
  },
  {
    "name": "LES Supper Club",
    "market": "NYC",
    "type": "Dinner",
    "neighborhood": "Lower East Side",
    "image_url": "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=900&q=80&auto=format&fit=crop",
    "price_tier": "$$$",
    "atmosphere": "Downtown dinner party",
    "best_for": "Turns Into Nightlife",
    "dress_code": "Cocktail",
    "description": "Creative-room dinner energy that sharpens into late-night DJs and cocktails."
  }
]$wtw_seed$::jsonb
  ) AS v (
    name text,
    market text,
    type text,
    neighborhood text,
    image_url text,
    price_tier text,
    atmosphere text,
    best_for text,
    dress_code text,
    description text
  )
)
INSERT INTO public.venues (
  name,
  market,
  type,
  neighborhood,
  image_url,
  price_tier,
  atmosphere,
  best_for,
  dress_code,
  description
)
SELECT
  v.name,
  v.market,
  v.type,
  v.neighborhood,
  v.image_url,
  v.price_tier,
  v.atmosphere,
  v.best_for,
  v.dress_code,
  v.description
FROM seed_venues v
WHERE NOT EXISTS (
  SELECT 1
  FROM public.venues e
  WHERE lower(coalesce(e.name, '')) = lower(coalesce(v.name, ''))
    AND e.market = v.market
);
